name: fuck
version: stable
version-script: git -C parts/fuck/build describe --abbrev=0 --tags
summary: AI-first command fixer for shell/terminal CLI with streamed explanations and Markdown rendering.
description: |
  Fuck tries to match a rule for the previous command,
  creates a new command using the matched rule and runs it.

grade: stable
confinement: classic

apps:
  fuck:
    command: bin/fuck
    environment:
        PYTHONIOENCODING: utf-8

parts:
  fuck:
    source: https://github.com/leeguooooo/fuck.git
    plugin: python
